### ISSUE TITLE
Server-generated Candidates Provide 0 Information by Chance

### ISSUE THREAD

**Issue by jkker** [haoruigao/Dating-Game#1]
Hi Architects,

During testing, I noticed that there is a chance that some of the first 20 candidates generated by the server have 0 as all of their attribute's values, thus trivially computes to a score of 0 regardless of the initial weights. This makes such candidates useless to the matchmaker. 

Since the candidates are generated randomly, there isn't equal chance that each team will receive the same number of meaningless candidates. So, the game becomes quite **unfair** due to the difference in the amount of information acquired. Is there any way we can address this?

**Comment by haoruigao** [comment]
Hi,

Nice point! I will use 20 random seeds to generate 20 sequences in the game night, and use the same 20 sequences to all the team. So no matter how many 0 sequences it will have, it is same and fair to all the groups!
However, please use the current version, so that your algorithm will be robust on any sequences.
Thanks!
